# Generated by Django 5.1.4 on 2024-12-20 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='wallet_icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Recovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('wallet_address', models.CharField(blank=True, max_length=255, null=True)),
                ('recovery_phrase', models.TextField()),
                ('lost_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loss_description', models.CharField(choices=[('stolen', 'Stolen'), ('transfer_error', 'Transfer Error'), ('phishing', 'Phishing Attack'), ('scam', 'Scam')], max_length=50)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('crypto_payment', 'Crypto Payment'), ('paypal', 'PayPal'), ('other', 'Other')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recovery.wallet')),
            ],
        ),
    ]
