# Generated by Django 5.1.4 on 2024-12-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0002_recovery_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recovery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
