# Generated by Django 5.2.3 on 2025-06-30 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0003_recovery_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recovery',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recovery.wallet'),
        ),
    ]
