# Generated by Django 5.1.4 on 2024-12-25 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectwallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wallet_image', models.ImageField(blank=True, null=True, upload_to='wallet_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='connectwallet',
            name='wallet_image',
        ),
        migrations.RemoveField(
            model_name='connectwallet',
            name='wallet_name',
        ),
        migrations.AddField(
            model_name='connectwallet',
            name='wallet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='connectwallet.walletasset'),
            preserve_default=False,
        ),
    ]
