# Generated by Django 5.1.4 on 2024-12-27 02:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectwallet', '0003_alter_connectwallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectwallet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='connectwallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='walletasset',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='walletasset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
